### ISSUE TITLE
Blog-entry doesn’t provide any explanation on source of data. 

### ISSUE THREAD

**Issue by UsagiBo** [expert26111/DockerSwarm#1]

**Comment by shrestaz** [comment]
Sources are now correctly cited with super scripts, where used.
Do you mean explanation on why we linked those sources are required? I don't think that's a common practice.

**Comment by UsagiBo** [comment]
I meant that it wasn't clear which part of the text your URL's refer to. This makes it difficult to find the arguments supporting your statements. 
Adding a title of the referenced material makes it clear what the URL points to. In addition adding a retrieval date for source material that can change over time is also a good practice.

**Comment by shrestaz** [comment]
### Update: 
Cited sources are now clearly label where used. Titles and dates of the sources (when provided) are also defined on the **Sources** part of the documentation.
