### ISSUE TITLE
Correct spelling mistakes

### ISSUE THREAD

**Issue by UsagiBo** [expert26111/DockerSwarm#2]
After putting the article through a spell checker, over 50 errors showed up.
I used [Grammarly] (https://app.grammarly.com/)

**Comment by shrestaz** [comment]
Spelling mistakes are fixed but there were around 5-8 mistakes.

Not all words are a part of their dictionary, for example, "Manish" and "Yoana".
Also commands such as `docker ls` is shown as spelling mistake since `ls` is not a valid word for them
